apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql8-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql8"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql8
spec:
  volumeName: pv-mysql8-volume # Force bind to this PV by name
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
