apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql-url: mysql-service
  ## default_auth is the name of config. This will be referred from volume mount definition
  default_auth: |
    [mysqld]
    default_authentication_plugin= mysql_native_password