apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-external-secret
spec:
  refreshPolicy: CreatedOnce
  target:
    name: mysql-secret
    creationPolicy: Orphan
    immutable: true
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        MYSQL_USER: {{ .Values.mysql.user | quote }}
        MYSQL_PASSWORD: '{{ "{{ .MYSQL_PASSWORD }}" }}'
        MYSQL_ROOT_PASSWORD: '{{ "{{ .MYSQL_ROOT_PASSWORD }}" }}'

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: mysql-password-generator