apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-external-secret
spec:
  refreshInterval: 0h

  secretStoreRef:
    name: fake-secret-store
    kind: ClusterSecretStore

  target:
    name: mysql-secret

  data:
    - secretKey: mysql-user
      remoteRef:
        key: /mysql/username
    - secretKey: mysql-password
      remoteRef:
        key: /mysql/password
    - secretKey: mysql-root-password
      remoteRef:
        key: /mysql/root-password
