apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: mysql-password-generator
spec:
  length: 24
  digits: 4
  symbols: 4
  symbolCharacters: "_%@#-"
  noUpper: false
  allowRepeat: true
  secretKeys:
    - MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD