# Default values for mysql8
global:
  mysqlPort: &mysqlPort 3306

replicas: 1

# MySQL Deployment
mysql:
  image:
    repository: mysql
    version: 8.4.0
    pullPolicy: IfNotPresent
  serviceUrl: mysql-service
  rootPassword: c2VjcmV0
  database: SPRING
  user: dG11c2Vy
  password: dG11c2Vy

podLabels: {}

service:
  type: ClusterIP
  port: *mysqlPort

resources:
  limits:
    cpu: 0.5
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 1Gi

livenessProbe:
  tcpSocket:
    port: *mysqlPort
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  tcpSocket:
    port: *mysqlPort
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5
startupProbe:
  tcpSocket:
    port: *mysqlPort
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 10